### ISSUE TITLE
Suggestion: Let us define which NPCs we want to kill

### ISSUE THREAD

**Issue by ivcosan** [Godofdrakes/barrows-potential#1]
Hi, would it be possible for us to define our own optimal NPCs? For example I like to kill 2 skeletons and 1 worm for 86% so I would define those exact 3 NPCs and the plugin would highlight and track only them.

**Comment by vyndvia** [comment]
Even being able to input a target percentage rather than a specific drop would be beneficial. I would love to use this plugin more if that was added.

**Comment by Godofdrakes** [comment]
Been busy with work and haven't found the time update this. 😅 

I've got NPC selection working locally. Basically the same as selecting which brothers to target. I need to find the time to put it through it's paces and then I'll get a pull request in to update the plugin version.

For the target percentage, what would be the use case there? Not that I don't want to add it. I just want to better understand where the current system falls short. I'm not aware of a case where you'd want to target a reward potential in-between one reward and another.

**Comment by Godofdrakes** [comment]
NPC selection will be available in the next release. Pull request [here](https://github.com/runelite/plugin-hub/pull/4641).
