### ISSUE TITLE
Plugin loads when logging in to guardians of the rift minigame.

### ISSUE THREAD

**Issue by withoutgettingwet** [Godofdrakes/barrows-potential#3]
Every time I log in to the lobby of GotR the plugin appears, saying I have a potential of 801- I'm not sure why.

**Comment by Godofdrakes** [comment]
Huh. That is odd. I don't think GOTR is even in the same zone as Barrows.

Does it happen when you hop worlds as well or only when you first log in?

**Comment by Godofdrakes** [comment]
Ah! Managed to reproduce the issue. If I start a barrows run (kill any brother), leave, enter the GOTR lobby, and then hop worlds the overlay appears.

Will try to get this fixed as soon as I can. Might be a few days though. Just got back from a flight and I'm still kinda jetlagged.

**Comment by Godofdrakes** [comment]
In the meantime if you finish your barrows run the overlay will stop appearing in GOTR. I've been doing GOTR for the last few weeks and had never seen this until I left a run incomplete.

**Comment by Godofdrakes** [comment]
Apologies, I _really_ dropped the ball on this one. I've just submitted [a pull request](https://github.com/runelite/plugin-hub/pull/5919) to the plugin hub with a fix for this.

**Comment by withoutgettingwet** [comment]
Nah mate you’re fine, this was pretty minor. Appreciate the fix!
